### ISSUE TITLE
Thanks for this awesome resource

### ISSUE THREAD

**Issue by ericvd-ucb** [JustinMShea/wooldridge#13]
I just found this awesome page https://justinmshea.github.io/wooldridge/articles/Introductory-Econometrics-Examples.html

Thanks for this amazing OER and open license!

**Comment by JustinMShea** [comment]
Thanks @ericvd-ucb 

The data package is intended to make learning Econometrics with R easier for students, while using the wooldridge text.

However, this accompanying text by Professor Florian Heiss, is a far better guide than my examples for using R with the wooldridge textbook. It can be found online here: https://www.urfie.net/

Justin
