### ISSUE TITLE
Not compatible with R version 3.6 and 4.0

### ISSUE THREAD

**Issue by Wolfherz** [JustinMShea/wooldridge#4]
> install.packages("woolridge")
Installing package into ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘woolridge’ is not available (for R version 3.6.0)

> install.packages("woolridge")
Warning in install.packages :
  package ‘woolridge’ is not available (for R version 4.0.0)

Please make woolridge available for newer versions of R. 
Thank you.

**Comment by JustinMShea** [comment]
It appears you have misspelled the package name in your call to `install.packages`, which is why the process errors out with "package not available". 

So the good news is, the `wooldridge` package does indeed build on the latest version of R and is backwards compatible to version 3.2.

Good luck,

**Comment by JustinMShea** [comment]
It appears you have misspelled the package name in your call to install.packages, which is why the process errors out with "package not available".

So the good news is, the wooldridge package does indeed build on the latest version of R and is backwards compatible to version 3.2.

Good luck,
